imap <silent> <ESC>[1;0P~ <C-R>=GSHandlePaste()<CR>
noremap <silent> <ESC>[1;0P~ "=GSHandlePaste()<CR>p
vmap <silent> <ESC>[1;0P~ "=GSHandlePaste()<CR>p

let g:last_vim_mode = '_'

if &term == "gsterm"
  set t_ts=]0;
  set t_fs=
  set ttymouse=sgr

	map <Esc>[<64;1;1m  <ScrollWheelUp>
	map! <Esc>[<64;1;1m <ScrollWheelUp>
	map <Esc>[<65;1;1m  <ScrollWheelDown>
	map! <Esc>[<65;1;1m <ScrollWheelDown>
endif

function! GSResetAfterPaste(x)
  set nopaste
endfunction

function! GSHandlePaste()
  let pf = expand("$VIMGS_PASTE_FILE")
  let txt = join(readfile(pf, "b"), "")
  let m = mode()
  set paste

  call timer_start(1, "GSResetAfterPaste")
  
  if m == 'n'
    return txt
  endif
  if m == 'i'
    return txt
  endif
  if m == 'v'
    return txt
  endif
endfunction

vnoremap <silent> <ESC>[1;0C~ y: call GSHandleCopy()<CR>
vnoremap <silent> <ESC>[1;0X~ d: call GSHandleCopy()<CR>

augroup vimgsevents
  au! SafeState * call GSChangeMode()
  au! BufEnter * call GSBufEnter()
augroup END

function! GSHandleSelection()
  let cf = expand("$VIMGS_COPY_FILE")
  let txt = getreg("@*")
  call writefile([txt], cf, "b")
  call writefile(["]X;SEL"], "/dev/stderr", "b")
endfunction

function! GSBufEnter()
  let p = expand("%:p")
  call writefile(["]X;PATH-".p.""], "/dev/stderr", "b")
endfunction

function! GSChangeMode()
  let m = mode()
  if (g:last_vim_mode != m)
    call writefile(["]X;MODE-".m.""], "/dev/stderr", "b")
    let g:last_vim_mode = m
  endif
endfunction

function! GSHandleCopy()
  let cf = expand("$VIMGS_COPY_FILE")
  let txt = getreg("@*")
  call writefile([txt], cf, "b")
  call writefile(["]X;COPY"], "/dev/stderr", "b")
endfunction
