imap <silent> <ESC>[1;0P~    <C-R>=GSHandlePaste('i')<CR>
noremap <silent> <ESC>[1;0P~ :call GSHandlePaste('n')<CR>
vmap <silent> <ESC>[1;0P~    :call GSHandlePaste('v')<CR>

set title

let g:last_vim_mode = '_'

if &term == "gsterm"
  set t_ts=]0;
  set t_fs=
  set ttymouse=sgr
  set mouse=a

  map <Esc>[<64;1;1M  <ScrollWheelUp>
  map! <Esc>[<64;1;1M <ScrollWheelUp>
  map <Esc>[<65;1;1M  <ScrollWheelDown>
  map! <Esc>[<65;1;1M <ScrollWheelDown>
endif

function! GSHandlePaste(m)
  let pf = expand("$VIMGS_PASTE_FILE")
  let txt = join(readfile(pf, "b"), "\n")
  set paste

  if a:m == 'n' 
    call setreg('"', txt)
    normal gP
  elseif a:m == 'v'
    call setreg('"', txt)
    normal gvp
  else
    return txt
  endif
endfunction

vnoremap <silent> <ESC>[1;0C~ y: call GSHandleCopy('c')<CR>
vnoremap <silent> <ESC>[1;0X~ d: call GSHandleCopy('x')<CR>
vnoremap <silent> <ESC>[1;0S~ y: call GSHandleCopy('s')<CR>

augroup vimgsevents
  au! SafeState * call GSChangeMode()
  au! BufEnter * call GSBufEnter()
  au! VimEnter * call GSBufEnter()
augroup END

function! GSBufEnter()
  let p = expand("%:p")
  call writefile(["]X;PATH-".p.""], "/dev/stderr", "b")
endfunction

function! GSChangeMode()
  set nopaste
  let m = mode()
  if (g:last_vim_mode != m)
    call writefile(["]X;MODE-".m.""], "/dev/stderr", "b")
    let g:last_vim_mode = m
  endif
endfunction

function! GSHandleCopy(m)
  let cf = expand("$VIMGS_COPY_FILE")
  let txt = getreg("@*")
  call writefile([txt], cf, "b")
  if (a:m == 'c')
    call writefile(["]X;COPY"], "/dev/stderr", "b")
    normal gv
  elseif (a:m == 's')
    call writefile(["]X;SELECTION"], "/dev/stderr", "b")
    normal gv
  elseif (a:m == 'x')
    call writefile(["]X;COPY"], "/dev/stderr", "b")
  endif
endfunction
